#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#catalogue:
#  path: /catalogue
#  controller: App\Controller\ArticleController::index

#fabrique:
#  path: /fabriques
#  controller: App\Controller\FabriqueController::index