<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFawvmva\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFawvmva/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFawvmva.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFawvmva\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFawvmva\appProdProjectContainer([
    'container.build_hash' => 'Fawvmva',
    'container.build_id' => '32ac58eb',
    'container.build_time' => 1584022949,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFawvmva');
